<<<<<<< HEAD
on:
  pull_request_review:
    branches: ["main"]
=======
on: pull_request_review
>>>>>>> 543d4aaf8800467cf4681117f118d9cf0879ef1f
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to test things
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: test action step
        uses: ./ # Uses an action in the root directory
        id: test
